DROP TABLE IF EXISTS floor_materials;
DROP TABLE IF EXISTS ceiling_materials;
DROP TABLE IF EXISTS wall_materials;
DROP TABLE IF EXISTS other_materials;
DROP TABLE IF EXISTS ceiling_products;
DROP TABLE IF EXISTS baffle_units;
DROP TABLE IF EXISTS wall_products;
DROP TABLE IF EXISTS recommended_reverb_times;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2),
    user_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL UNIQUE,
    active BOOLEAN,
    isadmin BOOLEAN,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);

CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now(),
    user_id TEXT
        REFERENCES users(user_name) ON DELETE CASCADE NOT NULL,
    user_name TEXT,
    customerName TEXT,
    projectName TEXT,
    room_height FLOAT,
    room_length FLOAT,
    room_width FLOAT,
    cLength FLOAT,
    cWidth FLOAT,
    wall1l FLOAT,
    wall1h FLOAT,
    wall2l FLOAT,
    wall2h FLOAT,
    wall3l FLOAT,
    wall3h FLOAT,
    wall4l FLOAT,
    wall4h FLOAT,
    selectedReverbTime FLOAT,
    selectedFloorMaterial INTEGER,
    selectedCeilingMaterial INTEGER,
    selectedWall1Material INTEGER,
    selectedWall2Material INTEGER,
    selectedWall3Material INTEGER,
    selectedWall4Material INTEGER,
    wall1sqft FLOAT,
    wall2sqft FLOAT,
    wall3sqft FLOAT,
    wall4sqft FLOAT,
    selectedOther1Material INTEGER,
    selectedOther2Material INTEGER,
    selectedOther3Material INTEGER,
    selectedOther4Material INTEGER,
    selectedOther5Material INTEGER,
    selectedOther6Material INTEGER,
    selectedOther7Material INTEGER,
    selectedOther8Material INTEGER,
    other1sqft FLOAT,
    other2sqft FLOAT,
    other3sqft FLOAT,
    other4sqft FLOAT,
    other5sqft FLOAT,
    other6sqft FLOAT,
    other7sqft FLOAT,
    other8sqft FLOAT,
    selectedCeiling1Product INTEGER,
    selectedCeiling2Product INTEGER,
    selectedCeiling3Product INTEGER,
    selectedCeiling4Product INTEGER,
    ceilingProd1sqft FLOAT,
    ceilingProd2sqft FLOAT,
    ceilingProd3sqft FLOAT,
    ceilingProd4sqft FLOAT,
    selectedBaffle1Unit INTEGER,
    selectedBaffle2Unit INTEGER,
    selectedBaffle3Unit INTEGER,
    baffle1sqft FLOAT,
    baffle2sqft FLOAT,
    baffle3sqft FLOAT,
    selectedWall1Product INTEGER,
    selectedWall2Product INTEGER,
    selectedWall3Product INTEGER,
    selectedWall4Product INTEGER,
    selectedWall5Product INTEGER,
    selectedWall6Product INTEGER,
    selectedWall7Product INTEGER,
    selectedWall8Product INTEGER,
    wallProd1sqft FLOAT,
    wallProd2sqft FLOAT,
    wallProd3sqft FLOAT,
    wallProd4sqft FLOAT,
    wallProd5sqft FLOAT,
    wallProd6sqft FLOAT,
    wallProd7sqft FLOAT,
    wallProd8sqft FLOAT
);


CREATE TABLE recommended_reverb_times (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 17),
    descript TEXT NOT NULL,
    min FLOAT NOT NULL,
    max FLOAT NOT NULL,
    active BOOLEAN
);

CREATE TABLE floor_materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 11),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN
);

CREATE TABLE ceiling_materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 12),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN

);

CREATE TABLE wall_materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 18),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN

);

CREATE TABLE other_materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 13),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN

);

CREATE TABLE ceiling_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 26),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN
);

CREATE TABLE wall_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 35),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN
);

CREATE TABLE baffle_units (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 5),
    descript TEXT NOT NULL,
    w FLOAT,
    l FLOAT,
    hz125 FLOAT NOT NULL,
    hz250 FLOAT NOT NULL,
    hz500 FLOAT NOT NULL,
    hz1000 FLOAT NOT NULL,
    hz2000 FLOAT NOT Null,
    hz4000 FLOAT NOT NULL,
    NRC FLOAT NOT NULL,
    active BOOLEAN
);
