INSERT INTO Stocks (symbol) VALUES ('JDST'), ('NUGT');
INSERT INTO subjects (name) VALUES ('gold'), ('dollar');
INSERT INTO sources (name) VALUES ('tradingview');


UPDATE sentiment_analysis
SET token_values = NULL;

TRUNCATE master_tokens RESTART IDENTITY CASCADE;

INSERT INTO master_tokens (term)
VALUES 
('Bullish on gold'),
('Bearish on gold'),
('Bullish on US dollar'),
('Bearish on US dollar'),
('Ongoing conflict in the Middle East'),
('Political instability in the US'),
('Economic instability in the US'),
('US interest rate hike'),
('US interest rate cut'),
('Increase in US inflation'),
('Decrease in US inflation'),
('Strong US job market'),
('Weak US job market'),
('Increase in gold mining'),
('Decrease in gold mining'),
('Increase in gold demand'),
('Decrease in gold demand'),
('Gold reserve changes'),
('US debt level'),
('Global economic stability'),
('Trade relations between US and China'),
('Trade relations between US and EU'),
('Natural disasters impacting economy'),
('Technological advancements in gold mining'),
('Technological advancements in currency security'),
('Geopolitical tensions affecting gold or dollar'),
('Changes in gold or dollar exchange rates'),
('Legislation affecting gold or dollar'),
('International sanctions affecting gold or dollar'),
('Central bank policies affecting gold or dollar'),
('Gold trading volume increase'),
('Gold trading volume decrease'),
('US dollar trading volume increase'),
('US dollar trading volume decrease'),
('Positive gold market forecast'),
('Negative gold market forecast'),
('Positive US dollar market forecast'),
('Negative US dollar market forecast'),
('Gold as a safe haven'),
('US economic recovery'),
('Global economic recovery'),
('Increase in global gold demand'),
('Decrease in global gold demand'),
('Stable US political climate'),
('Unstable US political climate'),
('Stable global political climate'),
('Unstable global political climate'),
('New gold discoveries'),
('Gold supply disruptions'),
('US dollar supply changes'),
('Federal Reserve policy changes'),
('Increase in global trade'),
('Decrease in global trade'),
('US trade deficit'),
('Gold price volatility'),
('US dollar price volatility'),
('Increase in consumer spending'),
('Decrease in consumer spending'),
('Gold investment sentiment'),
('US dollar investment sentiment'),
('Global monetary policy'),
('US fiscal policy'),
('Gold market regulation changes'),
('Currency market regulation changes'),
('Increase in manufacturing activity'),
('Decrease in manufacturing activity'),
('Rising energy prices'),
('Falling energy prices'),
('Global climate change policy'),
('US climate change policy'),
('Financial market uncertainty'),
('Gold market manipulation'),
('Currency market manipulation'),
('Changes in gold ETF holdings'),
('Changes in foreign exchange reserves'),
('US credit rating'),
('Global credit ratings'),
('Changes in commodity prices'),
('Terrorist activity affecting economy'),
('Blockchain and cryptocurrency impact'),
('Pandemic or health crisis impact'),
('Technological innovation in finance'),
('Housing market trends'),
('Banking industry trends'),
('Merger and acquisition activity affecting gold or dollar'),
('Competing currencies impact on US dollar'),
('Competing precious metals impact on gold'),
('Positive earnings reports'),
('Negative earnings reports'),
('Corporate governance issues'),
('Corporate tax rate changes'),
('Increase in capital market activity'),
('Decrease in capital market activity'),
('Emerging markets growth'),
('Emerging markets decline'),
('Rising global interest rates'),
('Falling global interest rates'),
('Global debt levels'),
('Currency devaluation'),
('Currency revaluation'),
('Changes in fiscal policy globally'),
('Changes in monetary policy globally'),
('Increase in consumer confidence'),
('Decrease in consumer confidence'),
('Increase in business confidence'),
('Decrease in business confidence'),
('Global infrastructure spending'),
('US infrastructure spending'),
('Environmental regulations affecting gold mining'),
('Environmental regulations affecting currency printing'),
('Innovations in gold recycling'),
('Innovations in digital currency'),
('Increase in global liquidity'),
('Decrease in global liquidity'),
('Labor market trends globally'),
('Labor market trends in the US'),
('Industrial production trends'),
('Increase in foreign direct investment'),
('Decrease in foreign direct investment'),
('Foreign exchange market trends'),
('Banking sector stability'),
('Banking sector instability'),
('Global savings rate'),
('US savings rate'),
('Global investment flows'),
('US investment flows'),
('Changes in retail sales'),
('Changes in industrial output'),
('Consumer price index trends'),
('Producer price index trends'),
('Global political alliances'),
('Global political discord'),
('Impact of climate change on gold mining'),
('Impact of climate change on economy'),
('Gold smuggling incidents'),
('New gold-backed financial products'),
('New digital currency initiatives'),
('Cybersecurity threats to financial markets'),
('Global cybersecurity policies'),
('US cybersecurity policies'),
('Renewable energy policies globally'),
('Renewable energy policies in the US'),
('Changes in global oil prices'),
('Changes in global energy prices'),
('Gold import/export restrictions'),
('Currency exchange restrictions'),
('Gold market fraud incidents'),
('Currency market fraud incidents'),
('Technological advancements in gold detection'),
('Technological advancements in financial transactions'),
('Central bank gold purchases'),
('Central bank gold sales'),
('Central bank currency interventions'),
('New trade agreements'),
('Trade disputes resolution'),
('Changes in import/export tariffs globally'),
('Changes in import/export tariffs in the US'),
('Impact of educational trends on economy'),
('Impact of technological trends on economy'),
('Impact of social trends on economy'),
('Impact of cultural trends on economy'),
('Changes in global poverty levels'),
('Changes in US poverty levels'),
('Global health trends affecting economy'),
('US health trends affecting economy'),
('Impact of global military conflicts'),
('Impact of US military conflicts'),
('Impact of human rights policies on economy'),
('Changes in global population demographics'),
('Changes in US population demographics'),
('Impact of global migration trends'),
('Impact of US migration trends'),
('Changes in global urbanization trends'),
('Changes in US urbanization trends'),
('Impact of artificial intelligence on finance'),
('Impact of machine learning on finance'),
('Impact of data analytics on finance'),
('Development of quantum computing'),
('Impact of quantum computing on finance'),
('Financial literacy trends globally'),
('Financial literacy trends in the US'),
('Global humanitarian crises'),
('US humanitarian crises'),
('Impact of space exploration on economy'),
('Impact of space exploration on gold'),
('Impact of space exploration on US dollar'),
('Impact of telecommunications advancements on economy'),
('Impact of 5G technology on economy'),
('Impact of virtual reality on economy'),
('Impact of augmented reality on economy'),
('Impact of blockchain technology on gold market'),
('Impact of blockchain technology on currency market'),
('Impact of autonomous vehicles on economy'),
('Impact of e-commerce trends on economy'),
('Impact of online banking trends on economy'),
('Impact of mobile payment trends on economy'),
('Impact of gig economy trends on economy'),
('Impact of sharing economy trends on economy'),
('Impact of subscription economy trends on economy'),
('Impact of automation on economy'),
('Impact of robotics on economy'),
('Impact of nanotechnology on economy'),
('Impact of biotechnology on economy'),
('Impact of clean technology on economy'),
('Impact of smart cities on economy'),
('Impact of sustainable development goals on economy'),
('Impact of universal basic income experiments'),
('Impact of privacy laws on finance'),
('Impact of anti-corruption measures on economy'),
('Impact of anti-money laundering measures on economy'),
('Impact of tax evasion measures on economy'),
('Impact of financial inclusivity initiatives on economy'),
('Impact of gender equality initiatives on economy'),
('Impact of income inequality measures on economy'),
('Impact of digital identity verification on finance'),
('Impact of financial regulation compliance on economy'),
('Environmental disaster impact'),
('Impact of Internet of Things (IoT) on economy'),
('Impact of big data on economy'),
('Impact of cloud computing on economy'),
('Impact of 3D printing on economy'),
('Impact of augmented reality on finance'),
('Impact of virtual reality on finance'),
('Impact of global population growth on economy'),
('Impact of aging population on economy'),
('Impact of youth bulge on economy'),
('Impact of urbanization on gold'),
('Impact of urbanization on US dollar'),
('Global food security trends'),
('Global water security trends');